name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install remark-cli@11 remark-preset-lint-consistent@5
      - name: Run markdown lint
        continue-on-error: true
        run: npx remark **/*.md --use remark-preset-lint-consistent --ignore node_modules
